'use strict';
// Run with NODE_PATH pointing at a jsdom installation. This is a DOM contract
// regression test with explicit fixtures, not a hardware/backend integration test.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {JSDOM} = require('jsdom');
const root = path.resolve(__dirname,'../src/glove_chirality/web');
let html = fs.readFileSync(path.join(root,'templates/index.html'),'utf8').replace('{% include "factory.html" %}',fs.readFileSync(path.join(root,'templates/factory.html'),'utf8')).replace(/\{%[\s\S]*?%\}/g,'').replace(/\{\{[\s\S]*?\}\}/g,'').replace('data-local=""','data-local="true"');
async function main() {
 const dom = new JSDOM(html,{url:'http://localhost:8765/#token=test-token',runScripts:'outside-only'});
 const w = dom.window, calls = [], timers = [], failures = []; let state = {can_edit:true,running:{},jobs:{},logs:[]};
 w.Headers = Headers; w.AbortSignal = AbortSignal; w.HTMLElement.prototype.scrollIntoView = function(){};
 w.HTMLDialogElement.prototype.showModal = function(){this.open=true;}; w.HTMLDialogElement.prototype.close = function(){this.open=false;};
 w.scrollTo = () => {}; w.matchMedia = () => ({matches:true}); w.alert = message => failures.push(message); w.confirm = () => true;
 w.setInterval = (fn,ms) => {timers.push({fn,ms});return timers.length;}; w.setTimeout = () => 1;
 w.fetch = async (url,options={}) => {
  calls.push({url,options}); let payload = {};
  if (url === '/api/state') payload=state;
  else if (url === '/api/factory/configs') payload={configs:[]};
  else if (url === '/api/factory/devices') payload={choices:['auto'],label:'test device'};
  else if (url.startsWith('/api/factory/checkpoints')) payload={checkpoints:[]};
  else if (url.startsWith('/api/comparison?')) payload={runs:[]};
  else if (url.startsWith('/api/config?')) payload={path:'configs/default.yaml',text:'test: true'};
  else if (url === '/api/run') payload={job_id:'test-job',slot:'pipeline'};
  else if (url === '/api/jobs/preflight') payload={ok:true,dataset:{counts:{total:4,classes:{left:2,right:2},sources:4},grouped_split:{train_count:2,validation_count:2},validity:{invalid_rows:[]},duplicates:{content:[]}}};
  else if (url.endsWith('/status')) payload={running:false,status:'idle',counters:{}};
  return {ok:true,status:200,headers:new Headers({'Content-Type':'application/json'}),json:async()=>payload};
 };
 let resumes=0, contexts=0, tones=0;
 w.AudioContext=class {constructor(){contexts++;this.state='suspended';this.currentTime=0;this.destination={};} async resume(){resumes++;this.state='running';} createOscillator(){return {frequency:{},connect(){return {connect(){}};},start(){tones++;},stop(){}};} createGain(){return {gain:{setValueAtTime(){},exponentialRampToValueAtTime(){}}};}};
 for(const file of ['alerts.js','jobs.js','workstation.js','app.js','inference.js','factory.js']) w.eval(fs.readFileSync(path.join(root,'static',file),'utf8'));
 const formValues = () => [...w.document.querySelectorAll('form')].map(form => [...form.elements].filter(el => el.name).map(el => [el.name,el.value,el.checked ?? null]).sort((a,b) => a[0].localeCompare(b[0])));
 const beforePresentation = formValues();
 w.eval(fs.readFileSync(path.join(root,'static/interface.js'),'utf8'));
 assert.deepEqual(formValues(),beforePresentation,'disclosure preserves every named control and value');
 w.document.dispatchEvent(new w.Event('DOMContentLoaded'));
 const flush=async()=>{for(let i=0;i<15;i++)await Promise.resolve();}; await flush();
 assert.equal(w.sessionStorage.getItem('grip-lan-token'),'test-token');
 assert(w.document.querySelectorAll('.action-form').length>=9,'existing workflows retained');
 assert([...w.document.querySelectorAll('.action-form')].every(f=>f.noValidate),'collect all server validation errors');
 const form = w.document.querySelector('[data-action="train"]');
 const visibleSections = () => [...w.document.querySelectorAll('main > .page-section')].filter(el => !el.hidden).map(el => el.id);
 assert.deepEqual(visibleSections(),['overview']);
 for(const id of ['factory','extract','layer-one','train','infer','explain','compare','logs']) {
  w.GripInterface.reveal(w.document.querySelector(`#${id} h1`));
  assert.deepEqual(visibleSections(),[id],'one visible workflow');
  assert.equal(w.document.querySelector('.nav-link[aria-current="page"]').hash,`#${id}`);
 }
 assert.equal(form.elements.learning_rate.closest('details').open,false);
 w.GripJobs.fail({checks:[{field:'learning_rate',status:'failed',message:'Invalid rate'}]},form,'Invalid rate');
 w.document.querySelector('#job-fix').click();
 w.dispatchEvent(new w.Event('hashchange'));
 assert.equal(form.elements.learning_rate.closest('details').open,true,'fix reveals advanced fields');
 assert.equal(w.document.activeElement,form.elements.learning_rate);
 assert.deepEqual(visibleSections(),['train']);
 form.elements.learning_rate.closest('details').open=false;
 assert.equal(w.document.querySelector('#factory-mode').value,'shadow');
 assert.equal(w.document.querySelector('#factory-manual-trigger').disabled,true);
 assert.equal(w.document.querySelector('#factory-amp').checked,false);
 w.document.querySelector('.nav-tools').open=true;
 w.location.hash='#compare'; w.dispatchEvent(new w.Event('hashchange'));
 assert.equal(w.document.querySelector('.nav-tools').open,false,'mobile tools close after navigation');
 assert.equal(w.document.querySelector('.nav-tools').classList.contains('active'),true);
 w.GripJobs.render({factory:{status:'idle'},inference:{status:'idle'}});
 assert.equal(w.document.querySelector('#global-status').textContent,'Ready · no active workflows');
 w.GripJobs.render({factory:{status:'faulted',fault:'fixture failure'}});
 assert.match(w.document.querySelector('#global-status').textContent,/Needs attention/);
 w.GripJobs.fail({checks:[{field:'manifest',status:'failed',message:'missing manifest'},{field:'output',status:'failed',message:'missing output'}]},form,'preflight failed');
 assert(form.elements.manifest.classList.contains('invalid-field'));
 assert(form.elements.output.classList.contains('invalid-field'));
 assert(!w.document.querySelector('[data-action="extract_dataset"]').elements.output.classList.contains('invalid-field'),'errors scoped to failed form');
 w.document.querySelector('#job-fix').click(); assert.equal(w.document.activeElement,form.elements.manifest);
 w.GripJobs.pending('j-1'); assert.match(w.document.querySelector('#global-status').textContent,/PREFLIGHT/);
 w.GripJobs.disconnected(new Error('offline')); assert.match(w.document.querySelector('#global-status').textContent,/CONNECTION LOST/);
 w.document.querySelector('#enable-alerts').click(); await flush();
 w.GripAlerts.tone('success','fixture:1'); w.GripAlerts.tone('success','fixture:1'); assert.equal(tones,2,'deduped double tone');
 w.document.querySelector('#enable-alerts').click(); await flush(); assert.equal(contexts,1,'reuses audio context'); assert.equal(resumes,2);
 state={...state,jobs:{pipeline:{job_id:'historic',action:'train',status:'completed'}}};
 const previous=tones; w.GripJobs.render(state); assert.equal(tones,previous,'bootstrap has no stale completion tone');
 form.elements.manifest.value='fixture/manifest.csv';
 w.document.querySelector('#training-dataset-summary button').click(); await flush();
 const validation=JSON.parse(calls.find(call=>call.url==='/api/jobs/preflight').options.body);
 assert.equal(validation.action,'train'); assert.equal(validation.manifest,'fixture/manifest.csv'); assert(!('payload' in validation),'preflight uses the actual flat server contract');
 assert.match(w.document.querySelector('#dataset-summary-cards').textContent,/LEFT2RIGHT2Total4/);
 w.GripWorkstation.render({running:{pipeline:true},jobs:{pipeline:{action:'train',stage:'Epoch completed',progress:{epoch:1,epochs:2,validation:{recall_per_class:[.8,.9],macro_recall:.85,macro_f1:.84}}}}});
 assert.match(w.document.querySelector('#workstation-monitor').textContent,/RIGHT recall90.00%/);
 w.GripJobs.render({...state,jobs:{pipeline:{job_id:'trained',action:'train',status:'succeeded',result:{checkpoint:'fixture/candidate.pt'}}}});
 [...w.document.querySelectorAll('#job-result button')].find(button=>button.textContent==='Run on test video').click();
 assert.equal(w.document.querySelector('#visual-checkpoint').value,'fixture/candidate.pt');
 assert.equal(w.document.querySelector('#visual-form').elements.source_type.value,'video');
 assert.equal(w.document.querySelector('#visual-source').value,'','camera index is not reused as a video path');
 w.dispatchEvent(new w.Event('hashchange'));
 assert.equal(w.document.activeElement,w.document.querySelector('#visual-source'),'result shortcut keeps source focus after routing');
 w.document.querySelector('#visual-form').dispatchEvent(new w.Event('submit',{cancelable:true})); await flush();
 const inference=calls.find(c=>c.url==='/api/inference/start'); assert(inference); assert.equal(JSON.parse(inference.options.body).mode,'shadow'); assert.equal(JSON.parse(inference.options.body).amp,false);
 w.document.querySelector('#factory-decision-label').textContent='WAITING';
 const originalFetch=w.fetch;
 w.fetch=async(url,options)=>url==='/api/factory/decision'?{ok:true,headers:new Headers({'Content-Type':'application/json'}),json:async()=>({phase:'REJECT'})}:originalFetch(url,options);
 await timers.find(t=>t.ms===100).fn(); assert.equal(w.document.querySelector('#factory-decision-label').textContent,'WAITING','detector phase cannot produce classified reject alarm');
 const event={event_id:'e-1',status:'accepted',prediction:'right',confidence:.9};
 let live={running:true,status:'running',mode:'shadow',session_id:'fixture-session',latest:event,events:[event],serial:{connected:false},threshold:.5};
 w.fetch=async(url,options)=>url==='/api/factory/status'?{ok:true,headers:new Headers({'Content-Type':'application/json'}),json:async()=>live}:originalFetch(url,options);
 await timers.find(t=>t.ms===400).fn();
 assert.equal(w.document.querySelector('#factory-decision-label').textContent,'RIGHT / REJECT');
 assert(w.document.querySelector('#factory-custom-config').disabled,'restart-required config is locked');
 assert(w.document.querySelector('#factory-manual-trigger').disabled,'physical trigger disabled in shadow');
 const passageRow=w.document.querySelector('#factory-events tr');
 live={...live,events:[{...event,ack:'OK'}]}; await timers.find(t=>t.ms===400).fn();
 assert.equal(w.document.querySelector('#factory-events tr'),passageRow,'passage rows retained for ACK updates');
 assert.match(passageRow.textContent,/ACK OK/);
 w.document.body.dataset.local='false';
 w.location.hash='#train'; w.GripInterface.refresh();
 assert.deepEqual(visibleSections(),['overview'],'host route unavailable to viewer');
 w.location.hash='#factory'; w.GripInterface.refresh();
 assert.deepEqual(visibleSections(),['factory'],'read-only factory route retained');
 const beforeViewer=calls.length; await timers.find(t=>t.ms===700).fn(); await timers.find(t=>t.ms===400).fn();
 assert(!calls.slice(beforeViewer).some(call=>/frame.jpg|crop.jpg|configs|checkpoints/.test(call.url)),'viewer never requests frames or host paths');
 assert(w.document.querySelector('#factory-preview').hidden);
 w.GripJobs.fail({checks:[{field:'secret',status:'failed',message:'secret path'}]},form,'private failure');
 assert(!w.document.querySelector('#job-error').open,'viewer cannot open raw diagnostic modal');
 assert.equal(failures.length,0);
 dom.window.close(); console.log('PASS: preserved form values, single-workflow navigation, advanced-field fixes, safe defaults, DOM contracts, preflight, audio, inference, reject/ACK gating and viewer isolation.');
}
main().catch(error=>{console.error(error);process.exitCode=1;});
